#ifndef CPEN391_L2A01_HPS_H
#define CPEN391_L2A01_HPS_H

#define AVALON_IMG_WRITER_RGBGRAY_COMPONENT_TYPE avalon_image_writer
#define AVALON_IMG_WRITER_RGBGRAY_COMPONENT_NAME avalon_img_writer_rgbgray
#define AVALON_IMG_WRITER_RGBGRAY_BASE 0x100
#define AVALON_IMG_WRITER_RGBGRAY_SPAN 64
#define AVALON_IMG_WRITER_RGBGRAY_END 0x13f

#endif /* CPEN391_L2A01_HPS_H */
