	soc_system u0 (
		.avalon_camera_export_height           (<connected-to-avalon_camera_export_height>),           //   avalon_camera_export.height
		.avalon_camera_export_startrow         (<connected-to-avalon_camera_export_startrow>),         //                       .startrow
		.avalon_camera_export_startcol         (<connected-to-avalon_camera_export_startcol>),         //                       .startcol
		.avalon_camera_export_colmode          (<connected-to-avalon_camera_export_colmode>),          //                       .colmode
		.avalon_camera_export_exposure         (<connected-to-avalon_camera_export_exposure>),         //                       .exposure
		.avalon_camera_export_rowsize          (<connected-to-avalon_camera_export_rowsize>),          //                       .rowsize
		.avalon_camera_export_colsize          (<connected-to-avalon_camera_export_colsize>),          //                       .colsize
		.avalon_camera_export_rowmode          (<connected-to-avalon_camera_export_rowmode>),          //                       .rowmode
		.avalon_camera_export_soft_reset_n     (<connected-to-avalon_camera_export_soft_reset_n>),     //                       .soft_reset_n
		.avalon_camera_export_width            (<connected-to-avalon_camera_export_width>),            //                       .width
		.avalon_camera_export_h_blanking       (<connected-to-avalon_camera_export_h_blanking>),       //                       .h_blanking
		.avalon_camera_export_v_blanking       (<connected-to-avalon_camera_export_v_blanking>),       //                       .v_blanking
		.avalon_camera_export_red_gain         (<connected-to-avalon_camera_export_red_gain>),         //                       .red_gain
		.avalon_camera_export_blue_gain        (<connected-to-avalon_camera_export_blue_gain>),        //                       .blue_gain
		.avalon_camera_export_green1_gain      (<connected-to-avalon_camera_export_green1_gain>),      //                       .green1_gain
		.avalon_camera_export_green2_gain      (<connected-to-avalon_camera_export_green2_gain>),      //                       .green2_gain
		.ccd_pixel_clock_bridge_clk            (<connected-to-ccd_pixel_clock_bridge_clk>),            // ccd_pixel_clock_bridge.clk
		.clk_50_clk                            (<connected-to-clk_50_clk>),                            //                 clk_50.clk
		.h2f_reset_reset_n                     (<connected-to-h2f_reset_reset_n>),                     //              h2f_reset.reset_n
		.hps_0_hps_io_hps_io_emac1_inst_TX_CLK (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TX_CLK>), //           hps_0_hps_io.hps_io_emac1_inst_TX_CLK
		.hps_0_hps_io_hps_io_emac1_inst_TXD0   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD0>),   //                       .hps_io_emac1_inst_TXD0
		.hps_0_hps_io_hps_io_emac1_inst_TXD1   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD1>),   //                       .hps_io_emac1_inst_TXD1
		.hps_0_hps_io_hps_io_emac1_inst_TXD2   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD2>),   //                       .hps_io_emac1_inst_TXD2
		.hps_0_hps_io_hps_io_emac1_inst_TXD3   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD3>),   //                       .hps_io_emac1_inst_TXD3
		.hps_0_hps_io_hps_io_emac1_inst_RXD0   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD0>),   //                       .hps_io_emac1_inst_RXD0
		.hps_0_hps_io_hps_io_emac1_inst_MDIO   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_MDIO>),   //                       .hps_io_emac1_inst_MDIO
		.hps_0_hps_io_hps_io_emac1_inst_MDC    (<connected-to-hps_0_hps_io_hps_io_emac1_inst_MDC>),    //                       .hps_io_emac1_inst_MDC
		.hps_0_hps_io_hps_io_emac1_inst_RX_CTL (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RX_CTL>), //                       .hps_io_emac1_inst_RX_CTL
		.hps_0_hps_io_hps_io_emac1_inst_TX_CTL (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TX_CTL>), //                       .hps_io_emac1_inst_TX_CTL
		.hps_0_hps_io_hps_io_emac1_inst_RX_CLK (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RX_CLK>), //                       .hps_io_emac1_inst_RX_CLK
		.hps_0_hps_io_hps_io_emac1_inst_RXD1   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD1>),   //                       .hps_io_emac1_inst_RXD1
		.hps_0_hps_io_hps_io_emac1_inst_RXD2   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD2>),   //                       .hps_io_emac1_inst_RXD2
		.hps_0_hps_io_hps_io_emac1_inst_RXD3   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD3>),   //                       .hps_io_emac1_inst_RXD3
		.hps_0_hps_io_hps_io_sdio_inst_CMD     (<connected-to-hps_0_hps_io_hps_io_sdio_inst_CMD>),     //                       .hps_io_sdio_inst_CMD
		.hps_0_hps_io_hps_io_sdio_inst_D0      (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D0>),      //                       .hps_io_sdio_inst_D0
		.hps_0_hps_io_hps_io_sdio_inst_D1      (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D1>),      //                       .hps_io_sdio_inst_D1
		.hps_0_hps_io_hps_io_sdio_inst_CLK     (<connected-to-hps_0_hps_io_hps_io_sdio_inst_CLK>),     //                       .hps_io_sdio_inst_CLK
		.hps_0_hps_io_hps_io_sdio_inst_D2      (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D2>),      //                       .hps_io_sdio_inst_D2
		.hps_0_hps_io_hps_io_sdio_inst_D3      (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D3>),      //                       .hps_io_sdio_inst_D3
		.hps_0_hps_io_hps_io_usb1_inst_D0      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D0>),      //                       .hps_io_usb1_inst_D0
		.hps_0_hps_io_hps_io_usb1_inst_D1      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D1>),      //                       .hps_io_usb1_inst_D1
		.hps_0_hps_io_hps_io_usb1_inst_D2      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D2>),      //                       .hps_io_usb1_inst_D2
		.hps_0_hps_io_hps_io_usb1_inst_D3      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D3>),      //                       .hps_io_usb1_inst_D3
		.hps_0_hps_io_hps_io_usb1_inst_D4      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D4>),      //                       .hps_io_usb1_inst_D4
		.hps_0_hps_io_hps_io_usb1_inst_D5      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D5>),      //                       .hps_io_usb1_inst_D5
		.hps_0_hps_io_hps_io_usb1_inst_D6      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D6>),      //                       .hps_io_usb1_inst_D6
		.hps_0_hps_io_hps_io_usb1_inst_D7      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D7>),      //                       .hps_io_usb1_inst_D7
		.hps_0_hps_io_hps_io_usb1_inst_CLK     (<connected-to-hps_0_hps_io_hps_io_usb1_inst_CLK>),     //                       .hps_io_usb1_inst_CLK
		.hps_0_hps_io_hps_io_usb1_inst_STP     (<connected-to-hps_0_hps_io_hps_io_usb1_inst_STP>),     //                       .hps_io_usb1_inst_STP
		.hps_0_hps_io_hps_io_usb1_inst_DIR     (<connected-to-hps_0_hps_io_hps_io_usb1_inst_DIR>),     //                       .hps_io_usb1_inst_DIR
		.hps_0_hps_io_hps_io_usb1_inst_NXT     (<connected-to-hps_0_hps_io_hps_io_usb1_inst_NXT>),     //                       .hps_io_usb1_inst_NXT
		.hps_0_hps_io_hps_io_uart0_inst_RX     (<connected-to-hps_0_hps_io_hps_io_uart0_inst_RX>),     //                       .hps_io_uart0_inst_RX
		.hps_0_hps_io_hps_io_uart0_inst_TX     (<connected-to-hps_0_hps_io_hps_io_uart0_inst_TX>),     //                       .hps_io_uart0_inst_TX
		.hps_0_hps_io_hps_io_i2c0_inst_SDA     (<connected-to-hps_0_hps_io_hps_io_i2c0_inst_SDA>),     //                       .hps_io_i2c0_inst_SDA
		.hps_0_hps_io_hps_io_i2c0_inst_SCL     (<connected-to-hps_0_hps_io_hps_io_i2c0_inst_SCL>),     //                       .hps_io_i2c0_inst_SCL
		.hps_0_hps_io_hps_io_gpio_inst_GPIO09  (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO09>),  //                       .hps_io_gpio_inst_GPIO09
		.hps_0_hps_io_hps_io_gpio_inst_GPIO35  (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO35>),  //                       .hps_io_gpio_inst_GPIO35
		.hps_0_hps_io_hps_io_gpio_inst_GPIO40  (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO40>),  //                       .hps_io_gpio_inst_GPIO40
		.hps_0_hps_io_hps_io_gpio_inst_GPIO53  (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO53>),  //                       .hps_io_gpio_inst_GPIO53
		.hps_0_hps_io_hps_io_gpio_inst_GPIO54  (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO54>),  //                       .hps_io_gpio_inst_GPIO54
		.hps_0_hps_io_hps_io_gpio_inst_GPIO61  (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO61>),  //                       .hps_io_gpio_inst_GPIO61
		.memory_mem_a                          (<connected-to-memory_mem_a>),                          //                 memory.mem_a
		.memory_mem_ba                         (<connected-to-memory_mem_ba>),                         //                       .mem_ba
		.memory_mem_ck                         (<connected-to-memory_mem_ck>),                         //                       .mem_ck
		.memory_mem_ck_n                       (<connected-to-memory_mem_ck_n>),                       //                       .mem_ck_n
		.memory_mem_cke                        (<connected-to-memory_mem_cke>),                        //                       .mem_cke
		.memory_mem_cs_n                       (<connected-to-memory_mem_cs_n>),                       //                       .mem_cs_n
		.memory_mem_ras_n                      (<connected-to-memory_mem_ras_n>),                      //                       .mem_ras_n
		.memory_mem_cas_n                      (<connected-to-memory_mem_cas_n>),                      //                       .mem_cas_n
		.memory_mem_we_n                       (<connected-to-memory_mem_we_n>),                       //                       .mem_we_n
		.memory_mem_reset_n                    (<connected-to-memory_mem_reset_n>),                    //                       .mem_reset_n
		.memory_mem_dq                         (<connected-to-memory_mem_dq>),                         //                       .mem_dq
		.memory_mem_dqs                        (<connected-to-memory_mem_dqs>),                        //                       .mem_dqs
		.memory_mem_dqs_n                      (<connected-to-memory_mem_dqs_n>),                      //                       .mem_dqs_n
		.memory_mem_odt                        (<connected-to-memory_mem_odt>),                        //                       .mem_odt
		.memory_mem_dm                         (<connected-to-memory_mem_dm>),                         //                       .mem_dm
		.memory_oct_rzqin                      (<connected-to-memory_oct_rzqin>),                      //                       .oct_rzqin
		.pll_camera_clks_24_clk                (<connected-to-pll_camera_clks_24_clk>),                //     pll_camera_clks_24.clk
		.pll_vga_clks_191_clk                  (<connected-to-pll_vga_clks_191_clk>),                  //       pll_vga_clks_191.clk
		.pll_vga_clks_25_clk                   (<connected-to-pll_vga_clks_25_clk>),                   //        pll_vga_clks_25.clk
		.rgbgray_img_data_valid                (<connected-to-rgbgray_img_data_valid>),                //            rgbgray_img.data_valid
		.rgbgray_img_input_data                (<connected-to-rgbgray_img_input_data>),                //                       .input_data
		.rgbgray_img_img_width                 (<connected-to-rgbgray_img_img_width>),                 //                       .img_width
		.rgbgray_img_img_height                (<connected-to-rgbgray_img_img_height>),                //                       .img_height
		.rgbgray_stream_reset_n_reset_n        (<connected-to-rgbgray_stream_reset_n_reset_n>)         // rgbgray_stream_reset_n.reset_n
	);

