#  CI workflow is triggered on pull requests on main branch
name: Parse response test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Parse Response
    runs-on: ubuntu-latest
    steps:
      # checkout repo on virtual machine
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Tests
        working-directory: ./sw/server
        run: |
          make parse_response && ./parse_test
